[project]
name = "pytest-unmagic-django"
version = "0.1.0"
description = "pytest-django support for pytest-unmagic"
license = {file = "LICENSE"}
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Testing",
]
dependencies = [
    "pytest",
    "pytest-unmagic",
    "pytest-django>=4.12",
]

[project.optional-dependencies]
test = [
    "django>=4.2,<6",
]

[project.urls]
Home = "https://github.com/dimagi/pytest-unmagic-django"

[project.entry-points.pytest11]
unmagic-django = "unmagic_django"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "unmagic_django"
